site_name: GalactixPE devs
docs_dir: docs
site_dir: .github/workflows/docs/web
markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets

nav:
  - Home: index.md
  - Exos:
    - exos/README.md
    - Models: exos/models.md
    - Cache: exos/caching.md
  - EasyUI:
    - easyui/README.md
  - Commando:
    - commando/README.md

theme:
  name: readthedocs


plugins:
  - section-index
