site_name: GalactixPE devs
docs_dir: docs
site_dir: .github/workflows/docs/web
markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - admonition
  - pymdownx.details

nav:
  - Home: index.md
  - Exos:
      - exos/README.md
      - Models: exos/models.md
      - Cache: exos/caching.md
  - EasyUI:
      - easyui/README.md
  - Commando:
      - commando/README.md

theme:
  name: material
  palette: 
  - scheme: default
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
  - scheme: slate 
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode

plugins:
  - section-index
